MVCBasics/Models/PeopleViewModel.cs
using MVCBasics.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Models
{
    public class PeopleViewModel
    {
        public PeopleViewModel()
        {
            
        }
        public List<Person> people = new List<Person>();
        public string SearchPhrase { get; set; }
        public CreatePersonViewModel CreatePerson { get; set; }
    }
}

MVCBasics/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Models
{
    public class Person
    {
        [Key]
        public int ID { get; set; }
        public string Name { get; set; }
        public int PhoneNumber { get; set; }
        public City City { get; set; }
        public List<PersonLanguage> Languages { get; set; } = new List<PersonLanguage>();
    }
}

MVCBasics/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using MVCBasics.Models;
using MVCBasics.Services;

namespace MVCBasics.Controllers
{
    public class CityController : Controller
    {
        ICityService CS;
        public CityController(ICityService _CS)
        {
            CS = _CS;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CityViewModel m)
        {
            CS.Add(m.CreateCity);
            //return View(m);
            return RedirectToAction("Index");
        }
        public IActionResult CityIndex(string search)
        {
            CityViewModel CVM = new CityViewModel();
            CVM.SearchPhrase = search;
            if (string.IsNullOrEmpty(CVM.SearchPhrase))
            {
                return PartialView("_CityListPartial", CS.All());
            }
            return PartialView("_CityListPartial", CS.FindBy(CVM));
        }
        public IActionResult CityDetails(int ID)
        {
            CreateCityViewModel CVPM = new CreateCityViewModel();
            CVPM.Model = CS.FindBy(ID);
            return PartialView("_CityDetailsPartial", CVPM);
        }
        public IActionResult Delete(int ID)
        {
            if (CS.Remove(ID))
            {
                ViewBag.Message = "Deleted";
                return Accepted();
            }
            ViewBag.Message = "Not Deleted";
            return NotFound();
        }
    }
}

MVCBasics/Controllers/CountryController.cs
using Microsoft.AspNetCore.Mvc;
using MVCBasics.Models;
using MVCBasics.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCBasics.Controllers
{
    public class CountryController : Controller
    {
        ICountryService CS;
        public CountryController(ICountryService _CS)
        {
            CS = _CS;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CountryIndex(string search)
        {
            CountryViewModel CVM = new CountryViewModel();
            CVM.SearchPhrase = search;
            if (string.IsNullOrEmpty(CVM.SearchPhrase))
            {
                return PartialView("_CountryListPartial", CS.All());
            }
            return PartialView("_CountryListPartial", CS.FindBy(CVM));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CountryViewModel m)
        {
            CS.Add(m.CreateCountry);
            //return View(m);
            return RedirectToAction("Index");
        }
        public IActionResult CountryDetails(int ID)
        {
            CreateCountryViewModel CVPM = new CreateCountryViewModel();
            CVPM.Model = CS.FindBy(ID);
            return PartialView("_CountryDetailsPartial", CVPM);
        }
        public IActionResult Delete(int ID)
        {
            if (CS.Remove(ID))
            {
                ViewBag.Message = "Deleted";
                return Accepted();
            }
            ViewBag.Message = "Not Deleted";
            return NotFound();
        }
    }
}

MVCBasics/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using MVCBasics.Models;
using MVCBasics.Services;

namespace MVCBasics.Controllers
{
    public class LanguageController : Controller
    {
        ILanguageService LS;
        public LanguageController(ILanguageService _LS)
        {
            LS = _LS;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LanguageViewModel m)
        {
            LS.Add(m.CreateLanguage);
            //return View(m);
            return RedirectToAction("Index");
        }
        public IActionResult AddToPerson(int LID,int PID)
        {
            LS.AddToPerson(LID, PID);
            return RedirectToAction("Index");
        }
        public IActionResult LanguageIndex(string search)
        {
            LanguageViewModel LVM = new LanguageViewModel();
            LVM.SearchPhrase = search;
            if (string.IsNullOrEmpty(LVM.SearchPhrase))
            {
                return PartialView("_LanguageListPartial", LS.All());
            }
            return PartialView("_LanguageListPartial", LS.FindBy(LVM));
        }
        public IActionResult LanguageDetails(int ID)
        {
            CreateLanguageViewModel LVPM = new CreateLanguageViewModel();
            LVPM.Model = LS.FindBy(ID);
            return PartialView("_LanguageDetailsPartial", LVPM);
        }
        public IActionResult Delete(int ID)
        {
            if (LS.Remove(ID))
            {
                
                ViewBag.Message = "Deleted";
                return Accepted();
                //return Json(new { success = true, responseText = "deleted" });
            }
            //return RedirectToAction("Index");
            //return Json(new { success = false, responseText = "not deleted" });
            ViewBag.Message = "Not Deleted";
            return NotFound();
        }
    }
}

MVCBasics/Controllers/PersonController.cs
using Microsoft.AspNetCore.Mvc;
using MVCBasics.Models;
using MVCBasics.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace MVCBasics.Controllers
{
    public class PersonController : Controller
    {
        //Constructor Injection--Fetching IPeopleService Object from Startup ConfigureServices
        IPeopleService ps;
        public PersonController(IPeopleService _ps)
        {
            ps = _ps;
        }
        public IActionResult Index(PeopleViewModel search)
        {
            //Use Below Code For Table Data If Not Using AJAX
            //if (string.IsNullOrEmpty(search.SearchPhrase))
            //{
            //    return View(ps.All());
            //}
            //return View(ps.FindBy(search));
            return View();
        }
        public IActionResult AddToPerson(int LID, int PID)
        {
            ps.AddToPerson(LID, PID);
            return RedirectToAction("Index");
        }
        //Use Below Method For Separate Create Page
        //public IActionResult Create()
        //{ 
        //    return View();
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PeopleViewModel m)
        {
            ps.Add(m.CreatePerson);
            //return View(m);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int ID)
        {
            CreatePersonViewModel CVPM = new CreatePersonViewModel();
            CVPM.Model = ps.FindBy(ID); 
            return View(CVPM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CreatePersonViewModel p)
        {
            ps.Edit(p.ID, p.Model);
            return View(p);
        }
        public IActionResult Delete(int ID)
        {
            if(ps.Remove(ID))
            {
                //return Content("<script language='javascript' type='text/javascript'>alert('Thanks for Feedback!');</script>");
                ViewBag.Message = "Deleted";
                return Accepted();
                //return Json(new { success = true, responseText = "deleted" });
            }
            //return RedirectToAction("Index");
            //return Json(new { success = false, responseText = "not deleted" });
            ViewBag.Message = "Not Deleted";
            return NotFound();
        }

        ///////////////////////// ACTIONS for AJAX
        ///
        public IActionResult PeopleIndex(string search)
        {
            PeopleViewModel PVM = new PeopleViewModel();
            PVM.SearchPhrase = search;
            if (string.IsNullOrEmpty(PVM.SearchPhrase))
            {
                return PartialView("_PeopleIndex", ps.All());
            }
            return PartialView("_PeopleIndex", ps.FindBy(PVM));
        }
        public IActionResult PersonDetails(int ID)
        {
            CreatePersonViewModel CVPM = new CreatePersonViewModel();
            CVPM.Model = ps.FindBy(ID);
            return PartialView("_PersonDetails",CVPM);
        }
        //public IActionResult GetData()
        //{
        //    var all = ps.All();
        //    List<Person> people = new List<Person>();
        //    people = all.people;
        //    Person p = new Person();
        //    p.ID = 1;
        //    p.Name = "Hamza";
        //    p.PhoneNumber = 00;
        //    p.city = "dff";
        //    people.Add(p);
        //    return PartialView("_Person",people.Last());
        //}
    }
}

MVCBasics/Views/Shared/_CityDetailsPartial.cshtml
@model MVCBasics.Models.CreateCityViewModel

<div>
    <h4>City Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
    </dl>
    <h4>People Living In This City</h4>
    <div id="PersonTable" class="table">
        <div>
            <hr />
            <div class="row">
                <div class="col-sm-2">
                    ID
                </div>
                <div class="col-sm-2">
                    Name
                </div>
                <div class="col-sm-2">
                    PhoneNumber
                </div>
                <div class="col-sm-2">
                    City
                </div>
            </div>
        </div>
        @*Showing Table Data with Partial View Using Razor*@
        @{
            var index = 0;
            @foreach (var item in Model.People)
            {
                <partial name="_Person" model="item" />
                index++;
            }
        }
    </div>
</div>
@*<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>*@

MVCBasics/Views/Shared/_CityListPartial.cshtml
@model MVCBasics.Models.CityViewModel
<div id="CityTable" class="table" style="background: skyblue; float: right; clear: both;">
    <div>
        <hr />
        <div class="row">
            <div class="col-sm-2">
                ID
            </div>
            <div class="col-sm-2">
                Name
            </div>
            <div class="col-sm-2">
                Country
            </div>
        </div>
    </div>
    @*Showing Table Data with Partial View Using Razor*@
    @{
        @foreach (var item in Model.Cities)
        {
            <partial name="_CityPartial" model="item" />
        }
    }
</div>

MVCBasics/Views/Shared/_CityPartial.cshtml
@model MVCBasics.Models.City

<div>
    <hr />
    <dl class="row">
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.Country.Name)
        </dd>
    </dl>
</div>

MVCBasics/Views/Shared/_CountryDetailsPartial.cshtml
@model MVCBasics.Models.CreateCountryViewModel

<div>
    <h4>City Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <h4>Cities In This Country</h4>
    <div id="PersonTable" class="table">
        <div>
            <hr />
            <div class="row">
                <div class="col-sm-2">
                    ID
                </div>
                <div class="col-sm-2">
                    Name
                </div>
            </div>
        </div>
        @*Showing Table Data with Partial View Using Razor*@
        @{
            @foreach (var item in Model.City)
            {
                <partial name="_CityPartial" model="item" />
            }
        }
    </div>
</div>
@*<div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

MVCBasics/Views/Shared/_CountryListPartial.cshtml
@model MVCBasics.Models.CountryViewModel
<div id="CityTable" class="table" style="background: skyblue; float: right; clear: both;">
    <div>
        <hr />
        <div class="row">
            <div class="col-sm-2">
                ID
            </div>
            <div class="col-sm-2">
                Name
            </div>
        </div>
    </div>
    @*Showing Table Data with Partial View Using Razor*@
    @{
        @foreach (var item in Model.Countries)
        {
            <partial name="_CountryPartial" model="item" />
        }
    }
</div>

MVCBasics/Views/Shared/_CountryPartial.cshtml
@model MVCBasics.Models.Country

<div>
    <hr />
    <dl class="row">
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>

MVCBasics/Views/Shared/_LanguageDetailsPartial.cshtml
@model MVCBasics.Models.CreateLanguageViewModel

<div>
    <h4>Language Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    <h4>People Speaking This Language</h4>
    <div id="PersonTable" class="table">
        <div>
            <hr />
            <div class="row">
                <div class="col-sm-2">
                    ID
                </div>
                <div class="col-sm-2">
                    Name
                </div>
                <div class="col-sm-2">
                    PhoneNumber
                </div>
                <div class="col-sm-2">
                    City
                </div>
            </div>
        </div>
        @*Showing Table Data with Partial View Using Razor*@
        @{
            var index = 0;
            @foreach (var item in Model.People)
            {
                <partial name="_Person" model="item.Person" />
                index++;
            }
        }
    </div>
</div>
@*<div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>*@

MVCBasics/Views/Shared/_LanguageListPartial.cshtml
@model MVCBasics.Models.LanguageViewModel
<div id="CityTable" class="table" style="background: skyblue; float: right; clear: both;">
    <div>
        <hr />
        <div class="row">
            <div class="col-sm-2">
                ID
            </div>
            <div class="col-sm-2">
                Name
            </div>
        </div>
    </div>
    @*Showing Table Data with Partial View Using Razor*@
    @{
        @foreach (var item in Model.Languages)
        {
            <partial name="_LanguagePartial" model="item" />
        }
    }
</div>

MVCBasics/Views/Shared/_LanguagePartial.cshtml
@model MVCBasics.Models.Language

<div>
    <hr />
    <dl class="row">
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>

MVCBasics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCBasics</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCBasics</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Countries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Index">Language</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCBasics - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVCBasics/Views/Shared/_PeopleIndex.cshtml
@model MVCBasics.Models.PeopleViewModel
<div id="PersonTable" class="table" style="background: skyblue; float: right; clear: both;">
    <div>
        <hr />
        <div class="row">
            <div class="col-sm-2">
                ID
            </div>
            <div class="col-sm-2">
                Name
            </div>
            <div class="col-sm-2">
                PhoneNumber
            </div>
            <div class="col-sm-2">
                City
            </div>
        </div>
    </div>
    @*Showing Table Data with Partial View Using Razor*@
    @{
            var index = 0;
            @foreach (var item in Model.people)
            {
                <partial  name="_Person" model="item"/>
                index++;
            }
        }
</div>

MVCBasics/Views/Shared/_Person.cshtml
@model MVCBasics.Models.Person
    <hr />
    <div class="row">
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.ID)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.Name)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.PhoneNumber)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.City.Name)
        </div>
        <div class="col-sm-1">
            @*@Html.ActionLink("Edit", "Edit", new { id = Model.ID })*@
        </div>
        <div class="col-sm-1">
            @*@Html.ActionLink("Details", "Edit", new { id = Model.ID })*@
        </div>
        <div class="col-sm-1">
            @*@Html.ActionLink("Delete", "Delete", new { id = Model.ID })*@
        </div>
    </div>

MVCBasics/Views/Shared/_PersonDetails.cshtml
@model MVCBasics.Models.CreatePersonViewModel

<div>
    <h4>Person Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City.Name)
        </dd>
    </dl>
    <h4>Person's Languages</h4>
    <div>
        <hr />
        <div class="row">
            <div class="col-sm-2">
                ID
            </div>
            <div class="col-sm-2">
                Name
            </div>
        </div>
    </div>
    @*Showing Table Data with Partial View Using Razor*@
    @{
        @foreach (var item in Model.Languages)
        {
            <partial name="_LanguagePartial" model="item.Language" />
        }
    }
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @*<a asp-action="Index">Back to List</a>*@
</div>